<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="LM-PC"><DocLocation><![CDATA[E:\UFT-Testing\ShopTask]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[ShopTask]]></DName>
<Res><![CDATA[Res18]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/1/18 - 14:36:50]]></Time>
<TimeTick>1453099010</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[导航到 https://123.150.11.173/login]]></Details>
<Time><![CDATA[2016/1/18 - 14:36:50]]></Time>
<TimeTick>1453099010</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" nType="导航到 https://123.150.11.173/login" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/1/18 - 14:36:51]]></Time>
<TimeTick>1453099011</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[会员登录]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:04]]></Time>
<TimeTick>1453099024</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[会员登录]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:04]]></Time>
<TimeTick>1453099024</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[j_username1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["test00002"]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:04]]></Time>
<TimeTick>1453099024</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="1" >
<Disp><![CDATA[j_username1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[j_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:10]]></Time>
<TimeTick>1453099030</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="Action1" SourceLine="2" >
<Disp><![CDATA[j_password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:16]]></Time>
<TimeTick>1453099036</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Action1" SourceLine="3" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Action1" SourceLine="1" >
<Disp><![CDATA[会员登录]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[完善信息 | 数字本草]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:21]]></Time>
<TimeTick>1453099041</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[卖家中心.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:21]]></Time>
<TimeTick>1453099041</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="Action1" SourceLine="4" >
<Disp><![CDATA[卖家中心.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="Action1" SourceLine="4" >
<Disp><![CDATA[完善信息 | 数字本草]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[数字本草]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:26]]></Time>
<TimeTick>1453099046</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[基础信息.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:26]]></Time>
<TimeTick>1453099046</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1" SourceLine="7" >
<Disp><![CDATA[基础信息.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["木木听雨"]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:33]]></Time>
<TimeTick>1453099053</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Action1" SourceLine="8" >
<Disp><![CDATA[name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[description.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["欢迎光临"]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:40]]></Time>
<TimeTick>1453099060</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="Action1" SourceLine="9" >
<Disp><![CDATA[description.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[contactName1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:45]]></Time>
<TimeTick>1453099065</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Action1" SourceLine="10" >
<Disp><![CDATA[contactName1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[contactPhone1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:50]]></Time>
<TimeTick>1453099070</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Action1" SourceLine="11" >
<Disp><![CDATA[contactPhone1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[contactName2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["张四"]]></Details>
<Time><![CDATA[2016/1/18 - 14:37:57]]></Time>
<TimeTick>1453099077</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="46" Source="Action1" SourceLine="13" >
<Disp><![CDATA[contactName2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[contactPhone2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1.538735239E+010"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:04]]></Time>
<TimeTick>1453099084</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" Source="Action1" SourceLine="14" >
<Disp><![CDATA[contactPhone2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[contactName3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["张五"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:11]]></Time>
<TimeTick>1453099091</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="Action1" SourceLine="15" >
<Disp><![CDATA[contactName3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[contactPhone3.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1.538735239E+010"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:18]]></Time>
<TimeTick>1453099098</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="Action1" SourceLine="16" >
<Disp><![CDATA[contactPhone3.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[telephone.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["022-27463085"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:25]]></Time>
<TimeTick>1453099105</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" Source="Action1" SourceLine="17" >
<Disp><![CDATA[telephone.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[fax.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["27463085"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:32]]></Time>
<TimeTick>1453099112</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Action1" SourceLine="18" >
<Disp><![CDATA[fax.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[qq.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["706031494"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:39]]></Time>
<TimeTick>1453099119</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="64" Source="Action1" SourceLine="19" >
<Disp><![CDATA[qq.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[countryIso.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["中国"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:44]]></Time>
<TimeTick>1453099124</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" Source="Action1" SourceLine="22" >
<Disp><![CDATA[countryIso.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[regionIso.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["天津"]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:49]]></Time>
<TimeTick>1453099129</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="Action1" SourceLine="23" >
<Disp><![CDATA[regionIso.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[cityCode]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityCode 对象的指定项。请确认指定项包含在对象的项集合中。]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:54]]></Time>
<TimeTick>1453099134</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[cityCode]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //SELECT[@id="address.city"]<br>|Visible Items = 0<br>Visible = -1<br>Name = cityCode<br>Items Count = 2<br>Html Id = address.city<br>default value = 请选择<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:54]]></Time>
<TimeTick>1453099134</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" status="Warning" nType="描述" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="73" status="Failed" nType="运行错误" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" status="Failed" Source="Action1" SourceLine="7" >
<Disp><![CDATA[数字本草]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="15" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[会员登录]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityCode 对象的指定项。请确认指定项包含在对象的项集合中。<BR>第 (25) 行: &quot;Browser(&quot;会员登录&quot;).Page(&quot;数字本草&quot;).WebList(&quot;cityCode&quot;).Select  DataTable(&quot;市级&quot;,&quot;Global&quot;)&quot;。 ]]></Details>
<Time><![CDATA[2016/1/18 - 14:38:54]]></Time>
<TimeTick>1453099134</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="75" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[会员登录]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:14]]></Time>
<TimeTick>1453099154</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[数字本草]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:14]]></Time>
<TimeTick>1453099154</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[cityCode]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityCode 对象的指定项。请确认指定项包含在对象的项集合中。]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:14]]></Time>
<TimeTick>1453099154</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[cityCode]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //SELECT[@id="address.city"]<br>|Visible Items = 0<br>Visible = -1<br>Name = cityCode<br>Items Count = 2<br>Html Id = address.city<br>default value = 请选择<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:14]]></Time>
<TimeTick>1453099154</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="81" status="Warning" nType="描述" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="80" status="Failed" nType="运行错误" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="79" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[数字本草]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="78" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[会员登录]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityCode 对象的指定项。请确认指定项包含在对象的项集合中。<BR>第 (25) 行: &quot;Browser(&quot;会员登录&quot;).Page(&quot;数字本草&quot;).WebList(&quot;cityCode&quot;).Select  DataTable(&quot;市级&quot;,&quot;Global&quot;)&quot;。 ]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:14]]></Time>
<TimeTick>1453099154</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[会员登录]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:21]]></Time>
<TimeTick>1453099161</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[数字本草]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:21]]></Time>
<TimeTick>1453099161</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[cityDistrictCode]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityDistrictCode 对象的指定项。请确认指定项包含在对象的项集合中。]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:21]]></Time>
<TimeTick>1453099161</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[cityDistrictCode]]></Obj>
<Details plainTxt="False" ><![CDATA[对象的物理描述:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //SELECT[@id="address.citydistrict"]<br>|Visible Items = 0<br>Visible = -1<br>Name = cityDistrictCode<br>Items Count = 17<br>Html Id = address.citydistrict<br>default value = 请选择<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:21]]></Time>
<TimeTick>1453099161</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" status="Warning" nType="描述" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityDistrictCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="87" status="Failed" nType="运行错误" Source="Action1" SourceLine="24" >
<Disp><![CDATA[cityDistrictCode]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[数字本草]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="85" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[会员登录]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[运行错误]]></Obj>
<Details plainTxt="False" ><![CDATA[无法标识 cityDistrictCode 对象的指定项。请确认指定项包含在对象的项集合中。<BR>第 (26) 行: &quot;Browser(&quot;会员登录&quot;).Page(&quot;数字本草&quot;).WebList(&quot;cityDistrictCode&quot;).Select  DataTable(&quot;地区&quot;,&quot;Global&quot;)&quot;。 ]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:21]]></Time>
<TimeTick>1453099161</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="89" status="Failed" Source="Action1" SourceLine="25" >
<Disp><![CDATA[运行错误]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[会员登录]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:26]]></Time>
<TimeTick>1453099166</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[数字本草]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:26]]></Time>
<TimeTick>1453099166</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[street.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["南开大学"]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:26]]></Time>
<TimeTick>1453099166</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="94" Source="Action1" SourceLine="25" >
<Disp><![CDATA[street.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[提交.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2016/1/18 - 14:39:31]]></Time>
<TimeTick>1453099171</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" Source="Action1" SourceLine="27" >
<Disp><![CDATA[提交.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="93" Source="Action1" SourceLine="25" >
<Disp><![CDATA[数字本草]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="92" Source="Action1" SourceLine="25" >
<Disp><![CDATA[会员登录]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2016/1/18 - 14:36:52" eTime="2016/1/18 - 14:39:31" passed="0" failed="6" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[Action1 摘要]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[ShopTask 迭代 1 (行 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2016/1/18 - 14:36:49" eTime="2016/1/18 - 14:39:31" passed="0" failed="6" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[测试 ShopTask 摘要]]></Disp>
</NodeArgs>
</Doc>
</Report>